name: check.yml
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: pcov
          tools: composer

      - name: Install Composer dependencies
        run: make install

      - name: Create database
        run: touch database/database.sqlite

      - name: Copy environment
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations and seeders
        run: php artisan migrate --force && php artisan db:seed --force

      - name: Install Breeze frontend
        run: |
          php artisan breeze:install blade
          sed -i "s/import '.\/bootstrap';//" resources/js/app.js
          npm install
          npm run build

      - name: Fix coding standards
        run: make lint-r

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
